name: Integration Test Workflow

on:
  push:
    branches: [ 'main', 'develop' ]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Run Flyway Migrations
      run: |
        docker run --network host --rm -v ${{ github.workspace }}/flyway/db/migrations:/flyway/sql flyway/flyway \
        -url=jdbc:postgresql://localhost:5432/${{ secrets.DB_NAME }} \
        -user=${{ secrets.DB_USER }} \
        -password=${{ secrets.DB_PASSWORD }} \
        migrate
        - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
    
    - name: Install dependencies
      run: |
        source venv/bin/activate
        pip install -r requirements.txt
    - name: Run Integration Tests
      env:
        DB_HOST: localhost
        DB_PORT: 5432
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: pytest tests/integration
