name: Integration Test Workflow

on:
  push:
    branches: [ 'main', 'develop' ]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: tests
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Generate Clickstream Data
      run: python src/clickstream_generator.py

    - name: Insert Data to Database
      env:
        DB_NAME: tests
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: localhost
        DB_PORT: 5432
      run: python src/data_inserter.py

    - name: Run Integration Tests
      env:
        DB_NAME: tests
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: localhost
        DB_PORT: 5432
      run: pytest tests/integration